// Standardized application error codes
// Used in API results to allow renderer to display localized error messages

export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  WRONG_PASSWORD: 'WRONG_PASSWORD',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED: 'MISSING_REQUIRED',

  // Students
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_NUMBER_EXISTS: 'STUDENT_NUMBER_EXISTS',
  QR_TOKEN_EXISTS: 'QR_TOKEN_EXISTS',
  STUDENT_ALREADY_ENROLLED: 'STUDENT_ALREADY_ENROLLED',

  // Attendance
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_CLOSED: 'SESSION_CLOSED',
  ALREADY_SCANNED: 'ALREADY_SCANNED',
  UNKNOWN_CARD: 'UNKNOWN_CARD',
  DISABLED_CARD: 'DISABLED_CARD',
  STUDENT_INACTIVE: 'STUDENT_INACTIVE',
  NOT_ENROLLED: 'NOT_ENROLLED',

  // Payments
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_CANCELLED: 'PAYMENT_ALREADY_CANCELLED',
  NEGATIVE_AMOUNT: 'NEGATIVE_AMOUNT',

  // Backup
  BACKUP_FAILED: 'BACKUP_FAILED',
  BACKUP_NOT_FOUND: 'BACKUP_NOT_FOUND',
  BACKUP_INVALID: 'BACKUP_INVALID',
  BACKUP_CORRUPTED: 'BACKUP_CORRUPTED',
  RESTORE_FAILED: 'RESTORE_FAILED',

  // Media
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  PATH_TRAVERSAL: 'PATH_TRAVERSAL',

  // Database
  DB_ERROR: 'DB_ERROR',
  UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
  FOREIGN_KEY: 'FOREIGN_KEY',

  // General
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  FIRST_RUN_REQUIRED: 'FIRST_RUN_REQUIRED',
} as const

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode]

export class AppError extends Error {
  code: ErrorCodeType
  constructor(code: ErrorCodeType, message: string) {
    super(message)
    this.code = code
    this.name = 'AppError'
  }
}
